function print_post_BONDLL_metrics(summary)

    col_names = {'TPR','FPR','MCC','FDR','beta_RMSE','Q_RMSE', ...
                 'ratio_same','ratio_opposite','n_true','comp_time'};

    row_names = {'BONDELL'};

    T = table( ...
        summary.BONDELL.TPR, ...
        summary.BONDELL.FPR, ...
        summary.BONDELL.MCC, ...
        summary.BONDELL.FDR, ...
        summary.BONDELL.beta_RMSE, ...
        summary.BONDELL.Q_RMSE, ...
        summary.BONDELL.ratio_same, ...
        summary.BONDELL.ratio_opposite, ...
        summary.BONDELL.n_true, ...
        summary.BONDELL.comp_time, ...
        'VariableNames', col_names, ...
        'RowNames', row_names);

    fprintf('\n============================================\n');
    fprintf('Post-fit summary metrics\n');
    fprintf('============================================\n');
    disp(T);
    fprintf('============================================\n');
end