function print_post_UNIQUE_metrics(summary)

    col_names = {'TPR','FPR','MCC','FDR','beta_RMSE','Q_RMSE', ...
                 'ratio_same','ratio_opposite','n_true', 'comp_time'};

    if isfield(summary, 'QRLASSO')
        row_names = {'UNIQUE'; 'QRLASSO'};

        T = table( ...
            [summary.UNIQUE.TPR;            summary.QRLASSO.TPR], ...
            [summary.UNIQUE.FPR;            summary.QRLASSO.FPR], ...
            [summary.UNIQUE.MCC;            summary.QRLASSO.MCC], ...
            [summary.UNIQUE.FDR;            summary.QRLASSO.FDR], ...
            [summary.UNIQUE.beta_RMSE;      summary.QRLASSO.beta_RMSE], ...
            [summary.UNIQUE.Q_RMSE;         summary.QRLASSO.Q_RMSE], ...
            [summary.UNIQUE.ratio_same;     summary.QRLASSO.ratio_same], ...
            [summary.UNIQUE.ratio_opposite; summary.QRLASSO.ratio_opposite], ...
            [summary.UNIQUE.n_true;         summary.QRLASSO.n_true], ...
            [summary.UNIQUE.comp_time;      summary.QRLASSO.comp_time], ...
            'VariableNames', col_names, ...
            'RowNames', row_names);
    else
        row_names = {'UNIQUE'};

        T = table( ...
            summary.UNIQUE.TPR, ...
            summary.UNIQUE.FPR, ...
            summary.UNIQUE.MCC, ...
            summary.UNIQUE.FDR, ...
            summary.UNIQUE.beta_RMSE, ...
            summary.UNIQUE.Q_RMSE, ...
            summary.UNIQUE.ratio_same, ...
            summary.UNIQUE.ratio_opposite, ...
            summary.UNIQUE.n_true, ...
            summary.UNIQUE.comp_time, ...
            'VariableNames', col_names, ...
            'RowNames', row_names);
    end

    fprintf('\n============================================\n');
    fprintf('Post-fit summary metrics\n');
    fprintf('============================================\n');
    disp(T);
    fprintf('============================================\n');
end